"""empty message

Revision ID: 699af7fdebe5
Revises: 
Create Date: 2024-08-26 21:49:40.324087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699af7fdebe5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
